apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: monitoring-app
  labels:
    app: monitoring-dashboard
    microservice: backend
    env: dev
    newlabel: newvalue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shankar0/project_assignment_backend:backend-fa794011a3bb5eea2fbaa1235adad8e7ba457245
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: monitoring-app
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
