apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monitoring-app
  labels:
    app: monitoring-dashboard
    microservice: frontend
    env: dev
    new: value
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shankar0/project_assignment_frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "150m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          envFrom:
          - configMapRef:
              name: frontend-env
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: monitoring-app
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
