name: Backend CI
on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend-ci:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Lint Go code
        run: go vet ./...

      - name: Run unit tests
        run: go test -v ./...

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/project_assignment_backend:${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project_assignment_backend:${{ github.sha }}
