name: Deploy to Minikube

on:
  push:
    branches:
      - '**'
    paths:
      - 'k8s/**'
  pull_request:
    paths:
      - 'k8s/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Minikube
        run: |
          # Use the default kubectl config, which should point to Minikube
          kubectl apply -f ./k8s