name: FRONTEND CI MAIN BRANCH

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.repository == 'hemanthravishankar/monitoring-dashboard'
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint Frontend code
        run: npm run lint || echo "No linter setup"

      - name: Run unit tests
        run: npm test || echo "No tests available"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }} .

      - name: 🔐 Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: 📦 Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }}

  update-deployment-pr:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.repository == 'hemanthravishankar/monitoring-dashboard'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update deployment image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }}|" k8s/frontend/deployment.yaml

      - name: Create Pull Request for deployment update
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ACTION_PAT }}
          commit-message: "Update frontend image to ${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }}"
          title: "Automated: Update frontend image to ${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }}"
          body: "This PR updates the frontend service image in `k8s/frontend/deployment.yaml` to the newly built image `${{ secrets.DOCKER_USERNAME }}/project_assignment_frontend:frontend-${{ github.sha }}`."
          branch: "automated/update-frontend-image"
          base: "main"