name: FRONTEND CI
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'frontend/**'

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint Frontend code
        run: npm run lint || echo "No linter setup"

      - name: Run unit tests
        run: npm test || echo "No tests available"

      - name: Build Docker image
        run: docker build -t project_assignment_frontend:frontend-${{ github.sha }} .