name: Backend CD to Main

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/frontend/**'

jobs:
  backend-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode and configure Kubeconfig
        run: |
          echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}

      - name: Deploy frontend
        run: |
          kubectl apply -f ./k8s/frontend/ -n monitoring-app